import { describe, expect, it } from 'vitest';
import {
  bandForAbility,
  correctForFalseAlarms,
  difficultyForRank,
  estimateAbility,
  MAX_DURATION_MS,
  MAX_ITEMS,
  MIN_ITEMS,
  probabilityCorrect,
  PRIOR_SD,
  rankForAbility,
  selectNextItem,
  shouldStop,
  TARGET_STANDARD_ERROR,
  type PlacementResponse,
} from './placement.ts';

describe('difficultyForRank', () => {
  it('rises with rank — rarer words are harder', () => {
    expect(difficultyForRank(100)).toBeLessThan(difficultyForRank(1000));
    expect(difficultyForRank(1000)).toBeLessThan(difficultyForRank(8000));
  });

  it('spreads the ranks a test actually asks about across the grid', () => {
    expect(difficultyForRank(100)).toBeLessThan(-2.5);
    expect(difficultyForRank(2000)).toBeCloseTo(0, 5);
    expect(difficultyForRank(8000)).toBeGreaterThan(1);
  });

  it('clamps to the ability grid instead of running off to negative infinity', () => {
    // the is easier than every learner — true, useless, and off-grid.
    expect(difficultyForRank(1)).toBeGreaterThanOrEqual(-4);
    expect(difficultyForRank(1)).toBe(-4);
  });

  it('is log-spaced: early ranks separate more than late ones', () => {
    const early = difficultyForRank(200) - difficultyForRank(100);
    const late = difficultyForRank(8100) - difficultyForRank(8000);
    expect(early).toBeGreaterThan(late * 10);
  });

  it('round-trips through rankForAbility', () => {
    for (const rank of [500, 2000, 8000]) {
      expect(rankForAbility(difficultyForRank(rank))).toBeCloseTo(rank, -1);
    }
  });

  it('survives a nonsense rank rather than returning NaN', () => {
    expect(Number.isFinite(difficultyForRank(0))).toBe(true);
    expect(Number.isFinite(difficultyForRank(-5))).toBe(true);
  });
});

describe('bandForAbility', () => {
  it('puts the default profile in band 3, matching decision D3', () => {
    // theta 0 is the intermediate English speaker who skipped placement.
    expect(bandForAbility(0)).toBe(3);
  });

  it('never drops below the first band', () => {
    expect(bandForAbility(-10)).toBe(1);
  });

  it('gives a stronger learner a higher band', () => {
    expect(bandForAbility(2)).toBeGreaterThan(bandForAbility(-2));
  });
});

describe('estimateAbility', () => {
  it('returns the prior when nothing has been answered', () => {
    // A learner who skipped placement needs no special case anywhere else.
    expect(estimateAbility([]).theta).toBeCloseTo(0, 5);
    expect(estimateAbility([]).standardError).toBeCloseTo(PRIOR_SD, 1);
  });

  it('moves up when hard items are answered correctly', () => {
    const responses: PlacementResponse[] = Array.from({ length: 10 }, () => ({
      difficulty: 1.5,
      correct: true,
    }));
    expect(estimateAbility(responses).theta).toBeGreaterThan(1);
  });

  it('moves down when easy items are missed', () => {
    const responses: PlacementResponse[] = Array.from({ length: 10 }, () => ({
      difficulty: -1.5,
      correct: false,
    }));
    expect(estimateAbility(responses).theta).toBeLessThan(-1);
  });

  it('does not diverge on an all-correct run, which MLE would', () => {
    const responses: PlacementResponse[] = Array.from({ length: 25 }, () => ({
      difficulty: 2,
      correct: true,
    }));
    const estimate = estimateAbility(responses);
    expect(Number.isFinite(estimate.theta)).toBe(true);
    expect(Number.isFinite(estimate.standardError)).toBe(true);
    expect(estimate.theta).toBeLessThan(4);
  });

  it('does not diverge on an all-wrong run either', () => {
    const responses: PlacementResponse[] = Array.from({ length: 25 }, () => ({
      difficulty: -2,
      correct: false,
    }));
    expect(Number.isFinite(estimateAbility(responses).theta)).toBe(true);
  });

  it('gets more precise as evidence accumulates', () => {
    const at = (count: number) =>
      estimateAbility(
        Array.from({ length: count }, (_, i) => ({ difficulty: 0, correct: i % 2 === 0 })),
      ).standardError;
    expect(at(20)).toBeLessThan(at(5));
    expect(at(5)).toBeLessThan(PRIOR_SD);
  });

  it('recovers the ability of a simulated learner', () => {
    // The estimator's job, stated plainly: given responses generated by a
    // learner of known ability, land near that ability.
    for (const trueTheta of [-1.5, 0, 1.5]) {
      const responses: PlacementResponse[] = [];
      for (let i = 0; i < 40; i++) {
        const difficulty = -2 + (i % 9) * 0.5;
        // Deterministic pseudo-response at the model's own probability.
        const p = probabilityCorrect(trueTheta, difficulty);
        responses.push({ difficulty, correct: (i * 0.618033) % 1 < p });
      }
      expect(estimateAbility(responses).theta).toBeCloseTo(trueTheta, 0);
    }
  });
});

describe('selectNextItem', () => {
  const pool = [
    { id: 'easy', difficulty: -2 },
    { id: 'medium', difficulty: 0 },
    { id: 'hard', difficulty: 2 },
  ];

  it('picks the item closest to the current estimate', () => {
    expect(selectNextItem(pool, 0, new Set())?.id).toBe('medium');
    expect(selectNextItem(pool, -1.9, new Set())?.id).toBe('easy');
    expect(selectNextItem(pool, 2.5, new Set())?.id).toBe('hard');
  });

  it('never asks the same item twice', () => {
    expect(selectNextItem(pool, 0, new Set(['medium']))?.id).not.toBe('medium');
  });

  it('returns null when the pool is exhausted', () => {
    expect(selectNextItem(pool, 0, new Set(['easy', 'medium', 'hard']))).toBeNull();
  });

  it('is deterministic when two items are equally informative', () => {
    const tied = [
      { id: 'b', difficulty: 1 },
      { id: 'a', difficulty: -1 },
    ];
    expect(selectNextItem(tied, 0, new Set())?.id).toBe(selectNextItem(tied, 0, new Set())?.id);
  });
});

describe('shouldStop (SPEC §4.2)', () => {
  it('stops at the item cap', () => {
    expect(shouldStop({ answered: MAX_ITEMS, elapsedMs: 0, standardError: 9 })).toBe(true);
  });

  it('stops at 90 seconds however uncertain the estimate still is', () => {
    expect(shouldStop({ answered: 3, elapsedMs: MAX_DURATION_MS, standardError: 9 })).toBe(true);
  });

  it('stops early once the estimate is precise enough', () => {
    expect(
      shouldStop({ answered: MIN_ITEMS, elapsedMs: 1000, standardError: TARGET_STANDARD_ERROR }),
    ).toBe(true);
  });

  it('does not stop on a precise-looking estimate from too few answers', () => {
    expect(shouldStop({ answered: 2, elapsedMs: 1000, standardError: 0.01 })).toBe(false);
  });

  it('keeps going while the estimate is still vague', () => {
    expect(shouldStop({ answered: 10, elapsedMs: 20_000, standardError: 0.8 })).toBe(false);
  });
});

describe('correctForFalseAlarms (SPEC §4.2)', () => {
  it('leaves an honest learner near their raw hit rate', () => {
    const result = correctForFalseAlarms({
      hits: 8,
      realShown: 10,
      falseAlarms: 0,
      pseudoShown: 5,
    });
    expect(result.corrected).toBeCloseTo(0.8);
  });

  it('penalises over-claiming', () => {
    // Without the correction, saying yes to everything scores 100%.
    const result = correctForFalseAlarms({
      hits: 10,
      realShown: 10,
      falseAlarms: 5,
      pseudoShown: 5,
    });
    expect(result.corrected).toBe(0);
  });

  it('discounts a learner who guesses on some of the pseudowords', () => {
    const honest = correctForFalseAlarms({ hits: 8, realShown: 10, falseAlarms: 0, pseudoShown: 10 });
    const guesser = correctForFalseAlarms({ hits: 8, realShown: 10, falseAlarms: 4, pseudoShown: 10 });
    expect(guesser.corrected).toBeLessThan(honest.corrected);
  });

  it('never returns a negative score', () => {
    const result = correctForFalseAlarms({ hits: 1, realShown: 10, falseAlarms: 9, pseudoShown: 10 });
    expect(result.corrected).toBeGreaterThanOrEqual(0);
  });

  it('handles a check that showed no pseudowords at all', () => {
    expect(
      correctForFalseAlarms({ hits: 5, realShown: 10, falseAlarms: 0, pseudoShown: 0 }).corrected,
    ).toBeCloseTo(0.5);
  });

  it('handles an empty tally without dividing by zero', () => {
    expect(
      correctForFalseAlarms({ hits: 0, realShown: 0, falseAlarms: 0, pseudoShown: 0 }).corrected,
    ).toBe(0);
  });
});
