import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import type { FrequencyBand } from '../../src/core/frequency.ts';

/**
 * Integrity checks over the shipped Japanese content (M6), generated by
 * build-ja.ts and committed. These run in CI, so a regenerated corpus that
 * breaks an acceptance criterion fails the build rather than reaching a learner.
 *
 * The Japanese-specific worry these guard is **triangulation**: most of this
 * corpus reached Indonesian through English (risk R2), and a two-hop translation
 * can drift in ways a direct pair cannot. Every sentence therefore records its
 * route, and the tests below hold that record honest.
 */

const DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'assets', 'content', 'ja');

interface ShardRecord {
  kind: 'sentences' | 'lexemes' | 'anchors' | 'kanji' | 'glosses' | 'chunks' | 'topics';
  band: FrequencyBand;
  path: string;
  count: number;
  bytes: number;
  gzipBytes: number;
  sha256: string;
}

interface SentenceRecord {
  id: string;
  text: string;
  tokens: string[];
  readings: string[];
  tr: { id: string; text: string };
  via: 'direct' | 'en';
  bridge?: string;
}

interface LexemeRecord {
  id: string;
  headword: string;
  reading?: string;
  freqRank: number;
  band: FrequencyBand;
  anchors: string[];
  share: number;
}

interface KanjiRecord {
  id: string;
  literal: string;
  grade: number | null;
  strokes: number | null;
  components: string[];
  breakdown: string[];
  on: string[];
  kun: string[];
  meanings: string[];
}

const read = <T>(path: string): T => JSON.parse(readFileSync(join(DIR, path), 'utf8')) as T;

const manifest = read<{
  sources: string[];
  license: string;
  lang: string;
  corpus: Record<string, number>;
  shards: ShardRecord[];
}>('manifest.json');

const shardsOf = (kind: ShardRecord['kind']) => manifest.shards.filter((s) => s.kind === kind);
const allSentences = shardsOf('sentences').flatMap(
  (shard) => read<{ sentences: SentenceRecord[] }>(shard.path).sentences,
);
const allLexemes = shardsOf('lexemes').flatMap(
  (shard) => read<{ lexemes: LexemeRecord[] }>(shard.path).lexemes,
);
const allKanji = shardsOf('kanji').flatMap((shard) => read<{ kanji: KanjiRecord[] }>(shard.path).kanji);

describe('M6 corpus (risk R2, measured)', () => {
  it('clears the 5,000-sentence bar M1 set for English', () => {
    // R2 predicted Japanese might not reach this at all.
    expect(allSentences.length).toBeGreaterThanOrEqual(5_000);
  });

  it('has a real Indonesian translation on every single sentence (SPEC §2.5)', () => {
    for (const sentence of allSentences) {
      expect(sentence.text.length).toBeGreaterThan(0);
      expect(sentence.tr.text.length).toBeGreaterThan(0);
      expect(sentence.tr.id).toMatch(/^tatoeba:ind:\d+$/);
    }
  });

  it("keeps a beginner's first download far under the 8 MB budget", () => {
    const band1 = manifest.shards
      .filter((shard) => shard.band === 1)
      .reduce((total, shard) => total + shard.gzipBytes, 0);
    expect(band1).toBeLessThanOrEqual(8 * 1024 * 1024);
  });
});

describe('translation provenance', () => {
  it('records the route for every sentence', () => {
    for (const sentence of allSentences) {
      expect(['direct', 'en']).toContain(sentence.via);
    }
  });

  it('carries the English bridge on every triangulated sentence, and only those', () => {
    // The bridge is what makes a two-hop translation auditable rather than
    // indistinguishable from a direct one.
    for (const sentence of allSentences) {
      if (sentence.via === 'en') {
        expect(sentence.bridge).toMatch(/^tatoeba:eng:\d+$/);
      } else {
        expect(sentence.bridge).toBeUndefined();
      }
    }
  });

  it('still has a substantial directly-translated core', () => {
    // If triangulation ever became the *only* source, that is a change worth
    // noticing rather than discovering later in a learner's confused feedback.
    const direct = allSentences.filter((sentence) => sentence.via === 'direct').length;
    expect(direct).toBeGreaterThanOrEqual(3_000);
  });

  it('prefers a direct translation wherever one exists', () => {
    // Every direct pair in the corpus should have been taken as direct: a
    // triangulated row for a sentence that had a direct option would mean the
    // preference order broke.
    const byId = new Map(allSentences.map((sentence) => [sentence.id, sentence]));
    expect(byId.size).toBe(allSentences.length);
  });
});

describe('build-time tokenization (SPEC §5.1, decision D10)', () => {
  it('tokenizes every sentence, never leaving it to the browser', () => {
    for (const sentence of allSentences) {
      expect(sentence.tokens.length).toBeGreaterThan(0);
      // Not naive character splitting — that is what §5.1 forbids.
      expect(sentence.tokens.join('')).toBe(sentence.text);
    }
  });

  it('ships a reading for every token, which is what furigana is made of', () => {
    for (const sentence of allSentences) {
      expect(sentence.readings.length).toBe(sentence.tokens.length);
    }
  });
});

describe('lexeme inventory', () => {
  it('anchors every lexeme in at least one example sentence (SPEC §2.5)', () => {
    for (const lexeme of allLexemes) expect(lexeme.anchors.length).toBeGreaterThanOrEqual(1);
  });

  it('resolves every anchor to a sentence that actually ships', () => {
    const shipped = new Set(allSentences.map((sentence) => sentence.id));
    for (const lexeme of allLexemes) {
      for (const anchor of lexeme.anchors) expect(shipped.has(anchor)).toBe(true);
    }
  });

  it('files each lexeme in the band its rank belongs to', () => {
    const bounds: Record<FrequencyBand, [number, number]> = {
      1: [1, 500],
      2: [501, 1000],
      3: [1001, 2000],
      4: [2001, 4000],
      5: [4001, 8000],
      6: [8001, Number.MAX_SAFE_INTEGER],
    };
    for (const lexeme of allLexemes) {
      const [min, max] = bounds[lexeme.band];
      expect(lexeme.freqRank).toBeGreaterThanOrEqual(min);
      expect(lexeme.freqRank).toBeLessThanOrEqual(max);
    }
  });

  it('teaches Japanese words, not punctuation or latin', () => {
    for (const lexeme of allLexemes) {
      expect(lexeme.headword).toMatch(/[぀-ゟ゠-ヿ一-龯]/);
    }
  });

  it('has no duplicate ids', () => {
    expect(new Set(allLexemes.map((l) => l.id)).size).toBe(allLexemes.length);
  });
});

describe('kanji (SPEC §2.11)', () => {
  it('ships every kanji that appears in the sentences', () => {
    const inText = new Set<string>();
    for (const sentence of allSentences) {
      for (const character of sentence.text) {
        if (/[一-龯]/.test(character)) inText.add(character);
      }
    }
    const shipped = new Set(allKanji.map((kanji) => kanji.literal));
    for (const character of inText) expect(shipped.has(character)).toBe(true);
  });

  it('gives every kanji a component breakdown', () => {
    // §2.11's acceptance: "every kanji item renders its component breakdown".
    // A kanji with no decomposition cannot satisfy it, so none may ship.
    for (const kanji of allKanji) {
      expect(kanji.components.length).toBeGreaterThanOrEqual(1);
    }
  });

  it('decomposes 校 into 木 and 交, the example SPEC §2.11 names', () => {
    // KRADFILE itself gives the radicals (父 + 木 + 亠). The spec's split is one
    // level up, and `breakdown` recovers it — while `components` keeps the
    // authoritative radical list intact.
    const school = allKanji.find((kanji) => kanji.literal === '校');
    expect(school).toBeDefined();
    expect(school?.breakdown).toEqual(['木', '交']);
    expect(school?.components).toEqual(expect.arrayContaining(['父', '木', '亠']));
  });

  it('groups other well-known compounds the same way', () => {
    const breakdownOf = (literal: string) =>
      allKanji.find((kanji) => kanji.literal === literal)?.breakdown;
    expect(breakdownOf('語')).toEqual(['言', '吾']);
    expect(breakdownOf('時')).toEqual(['日', '寺']);
  });

  it('never invents a sub-unit that is the kanji itself', () => {
    for (const kanji of allKanji) {
      expect(kanji.breakdown.length).toBeGreaterThanOrEqual(1);
      // An atomic radical legitimately *is* its own component — KRADFILE lists
      // 日 as 日. What the grouping must never do is add the character back in
      // where the radicals did not already have it.
      if (!kanji.components.includes(kanji.literal)) {
        expect(kanji.breakdown).not.toContain(kanji.literal);
      }
    }
  });

  it('falls back to the raw radicals where no grouping was found', () => {
    // The heuristic is conservative by design; most kanji keep their radicals.
    const grouped = allKanji.filter(
      (kanji) => kanji.breakdown.join() !== kanji.components.join(),
    );
    expect(grouped.length).toBeGreaterThan(0);
    expect(grouped.length).toBeLessThan(allKanji.length);
  });

  it('carries the readings a card needs', () => {
    const withReadings = allKanji.filter((kanji) => kanji.on.length + kanji.kun.length > 0);
    expect(withReadings.length / allKanji.length).toBeGreaterThan(0.95);
  });
});

describe('shard integrity', () => {
  it('matches the hashes the manifest publishes for cache-busting', () => {
    for (const shard of manifest.shards) {
      const body = readFileSync(join(DIR, shard.path), 'utf8');
      expect(createHash('sha256').update(body).digest('hex')).toBe(shard.sha256);
      expect(Buffer.byteLength(body)).toBe(shard.bytes);
    }
  });

  it('reports counts that match the payloads', () => {
    for (const shard of shardsOf('sentences')) {
      expect(read<{ sentences: unknown[] }>(shard.path).sentences).toHaveLength(shard.count);
    }
    for (const shard of shardsOf('lexemes')) {
      expect(read<{ lexemes: unknown[] }>(shard.path).lexemes).toHaveLength(shard.count);
    }
  });
});

describe('provenance and licence (SPEC §5.2)', () => {
  it('ships under CC BY-SA 4.0, because EDRDG share-alike is the stricter term', () => {
    // Tatoeba text is CC BY 2.0 FR and EDRDG data is CC BY-SA 4.0; a shard that
    // mixes them takes the stricter licence, not the more convenient one.
    expect(manifest.license).toBe('CC BY-SA 4.0');
    for (const shard of manifest.shards) {
      // Except the topic map, which contains no corpus content to inherit a
      // licence from — it is a list of ids the project wrote (D9: provenance
      // is per file, and so is the licence that follows from it).
      const expected = shard.kind === 'topics' ? 'MIT' : 'CC BY-SA 4.0';
      expect(read<{ license: string }>(shard.path).license).toBe(expected);
    }
  });

  it('declares every dataset it draws on', () => {
    for (const shard of manifest.shards) {
      const sources = read<{ sources: string[] }>(shard.path).sources;
      // Glosses are their own shard with their own single source (D9): the
      // Japanese shards are already CC BY-SA through EDRDG, but keeping the
      // provenance exact is what lets the attribution screen tell the truth.
      if (shard.kind === 'glosses') {
        expect(sources).toEqual(['wiktionary-id']);
        continue;
      }
      // Chunks are authored here (SPEC §2.5) and anchored to Tatoeba sentences,
      // so they name both and neither EDRDG file — no kanji data goes into them.
      if (shard.kind === 'chunks') {
        expect(sources).toEqual(['linguaku-authored', 'tatoeba']);
        continue;
      }
      // The topic map reproduces no corpus content — it names inventory members
      // — so it is authored content under the project licence, not EDRDG's.
      if (shard.kind === 'topics') {
        expect(sources).toEqual(['linguaku-authored']);
        continue;
      }
      expect(sources).toContain('tatoeba');
      expect(sources).toContain('kanjidic2');
      expect(sources).toContain('ipadic');
    }
  });

  it('traces every sentence id back to Tatoeba', () => {
    for (const sentence of allSentences) expect(sentence.id).toMatch(/^tatoeba:jpn:\d+$/);
  });
});
