import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import type { FrequencyBand } from '../../src/core/frequency.ts';

/**
 * Integrity checks over the *shipped* content in assets/content/en, which is
 * generated by build-en.ts and committed (SPEC §5.3). These run in CI, so a
 * regenerated corpus that breaks an M1 acceptance criterion fails the build
 * rather than reaching a learner.
 */

const CONTENT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'assets', 'content', 'en');

interface ShardRecord {
  kind: 'sentences' | 'lexemes' | 'anchors' | 'glosses' | 'passages' | 'chunks' | 'topics';
  band: FrequencyBand;
  path: string;
  count: number;
  bytes: number;
  gzipBytes: number;
  sha256: string;
}

interface Manifest {
  sources: string[];
  lang: string;
  corpus: Record<string, number>;
  shards: ShardRecord[];
}

interface SentenceRecord {
  id: string;
  text: string;
  difficulty: number;
  tr: { id: string; text: string };
}

interface LexemeRecord {
  id: string;
  headword: string;
  freqRank: number;
  band: FrequencyBand;
  anchors: string[];
}

const readShard = <T>(path: string): T => JSON.parse(readFileSync(join(CONTENT_DIR, path), 'utf8')) as T;

const manifest = readShard<Manifest>('manifest.json');
const sentenceShards = manifest.shards.filter((shard) => shard.kind === 'sentences');
const lexemeShards = manifest.shards.filter((shard) => shard.kind === 'lexemes');

const allSentences = sentenceShards.flatMap(
  (shard) => readShard<{ sentences: SentenceRecord[] }>(shard.path).sentences,
);
const allLexemes = lexemeShards.flatMap(
  (shard) => readShard<{ lexemes: LexemeRecord[] }>(shard.path).lexemes,
);

describe('M1 acceptance', () => {
  it('ships at least 5,000 banded English sentences with Indonesian translations', () => {
    expect(allSentences.length).toBeGreaterThanOrEqual(5_000);
    for (const sentence of allSentences) {
      expect(sentence.text.length).toBeGreaterThan(0);
      expect(sentence.tr.text.length).toBeGreaterThan(0);
    }
  });

  it("keeps a beginner's first download far under the 8 MB budget", () => {
    const beginnerBytes = manifest.shards
      .filter((shard) => shard.band === 1)
      .reduce((total, shard) => total + shard.gzipBytes, 0);
    expect(beginnerBytes).toBeLessThanOrEqual(8 * 1024 * 1024);
  });
});

describe('provenance (SPEC §5.2)', () => {
  it('declares its source on the manifest and on every shard', () => {
    expect(manifest.sources).toEqual(['tatoeba']);
    for (const shard of manifest.shards) {
      const payload = readShard<{ sources: string[]; license?: string }>(shard.path);
      // Provenance is per file (D9), and the gloss shards are the reason that
      // matters: they are Wiktionary-derived and share-alike, so folding them
      // into a Tatoeba shard would quietly upgrade the whole English corpus to
      // CC BY-SA. Separate files, separate licences.
      if (shard.kind === 'glosses') {
        expect(payload.sources).toEqual(['wiktionary-id']);
        expect(payload.license).toBe('CC BY-SA 4.0');
      } else if (shard.kind === 'topics') {
        // The topic map is authored here and derives from no corpus at all: it
        // names members of the inventory rather than reproducing any of it.
        expect(payload.sources).toEqual(['linguaku-authored']);
        expect(payload.license).toBe('MIT');
      } else if (shard.kind === 'chunks') {
        // Authored phrases (linguaku-authored) taught through Tatoeba
        // sentences: provenance is per file, and this file has two sources.
        expect(payload.sources).toEqual(['linguaku-authored', 'tatoeba']);
      } else if (shard.kind === 'passages') {
        expect(payload.sources).toEqual(['wikipedia-simple-en']);
        expect(payload.license).toBe('CC BY-SA 4.0');
      } else {
        expect(payload.sources).toEqual(['tatoeba']);
        expect(payload.license).toBe('CC BY 2.0 FR');
      }
    }
  });

  it('traces every sentence id back to a Tatoeba id', () => {
    for (const sentence of allSentences) {
      expect(sentence.id).toMatch(/^tatoeba:eng:\d+$/);
      expect(sentence.tr.id).toMatch(/^tatoeba:ind:\d+$/);
    }
  });
});

describe('shard integrity', () => {
  it('matches the hashes the manifest publishes for cache-busting', () => {
    for (const shard of manifest.shards) {
      const body = readFileSync(join(CONTENT_DIR, shard.path), 'utf8');
      expect(createHash('sha256').update(body).digest('hex')).toBe(shard.sha256);
      expect(Buffer.byteLength(body)).toBe(shard.bytes);
    }
  });

  it('reports counts that match the payloads', () => {
    for (const shard of sentenceShards) {
      expect(readShard<{ sentences: unknown[] }>(shard.path).sentences).toHaveLength(shard.count);
    }
    for (const shard of lexemeShards) {
      expect(readShard<{ lexemes: unknown[] }>(shard.path).lexemes).toHaveLength(shard.count);
    }
  });

  it('has no duplicate sentence or lexeme ids across shards', () => {
    expect(new Set(allSentences.map((s) => s.id)).size).toBe(allSentences.length);
    expect(new Set(allLexemes.map((l) => l.id)).size).toBe(allLexemes.length);
  });
});

describe('pseudowords (SPEC §4.2)', () => {
  const pseudowords = readShard<{ sources: string[]; words: string[] }>('pseudowords.json');
  const headwords = new Set(allLexemes.map((lexeme) => lexeme.headword));

  it('ships enough of them for a 25-item placement run', () => {
    expect(pseudowords.words.length).toBeGreaterThanOrEqual(50);
  });

  it('are all plausible word shapes', () => {
    for (const word of pseudowords.words) expect(word).toMatch(/^[a-z]{4,9}$/);
  });

  it('contains no word we actually teach', () => {
    // A pseudoword that is really a word turns a hit into a false alarm and
    // corrupts the correction it exists to support.
    for (const word of pseudowords.words) expect(headwords.has(word)).toBe(false);
  });

  it('has no duplicates', () => {
    expect(new Set(pseudowords.words).size).toBe(pseudowords.words.length);
  });

  it('declares its provenance like every other shard', () => {
    expect(pseudowords.sources).toEqual(['tatoeba']);
  });
});

describe('anchor shards', () => {
  const anchorShards = manifest.shards.filter((shard) => shard.kind === 'anchors');

  it('exist for every band that has lexemes', () => {
    const lexemeBands = new Set(lexemeShards.map((shard) => shard.band));
    const anchorBands = new Set(anchorShards.map((shard) => shard.band));
    for (const band of lexemeBands) expect(anchorBands.has(band)).toBe(true);
  });

  it('cover every anchor the lexemes in that band point at', () => {
    // The session path reads only these, so a missing anchor is an item that
    // cannot be taught (SPEC §2.5).
    for (const shard of lexemeShards) {
      const lexemes = readShard<{ lexemes: LexemeRecord[] }>(shard.path).lexemes;
      const anchorPath = anchorShards.find((a) => a.band === shard.band)?.path;
      expect(anchorPath).toBeTruthy();
      const available = new Set(
        readShard<{ sentences: SentenceRecord[] }>(anchorPath!).sentences.map((s) => s.id),
      );
      for (const lexeme of lexemes) {
        for (const anchor of lexeme.anchors) expect(available.has(anchor)).toBe(true);
      }
    }
  });

  it('are far smaller than the full sentence shards they stand in for', () => {
    const anchorBytes = anchorShards.reduce((sum, shard) => sum + shard.gzipBytes, 0);
    const sentenceBytes = sentenceShards.reduce((sum, shard) => sum + shard.gzipBytes, 0);
    expect(anchorBytes).toBeLessThan(sentenceBytes);
  });
});

describe('lexeme inventory', () => {
  it('anchors every lexeme in at least one example sentence (SPEC §2.5)', () => {
    for (const lexeme of allLexemes) {
      expect(lexeme.anchors.length).toBeGreaterThanOrEqual(1);
    }
  });

  it('resolves every anchor to a sentence that actually ships', () => {
    const shipped = new Set(allSentences.map((sentence) => sentence.id));
    for (const lexeme of allLexemes) {
      for (const anchor of lexeme.anchors) expect(shipped.has(anchor)).toBe(true);
    }
  });

  it('files each lexeme in the band its rank belongs to', () => {
    const bounds: Record<FrequencyBand, [number, number]> = {
      1: [1, 500],
      2: [501, 1000],
      3: [1001, 2000],
      4: [2001, 4000],
      5: [4001, 8000],
      6: [8001, Number.MAX_SAFE_INTEGER],
    };
    for (const lexeme of allLexemes) {
      const [min, max] = bounds[lexeme.band];
      expect(lexeme.freqRank).toBeGreaterThanOrEqual(min);
      expect(lexeme.freqRank).toBeLessThanOrEqual(max);
    }
  });

  it('teaches no placeholder names as vocabulary', () => {
    // Tatoeba's corpus makes `tom` the 3rd most frequent token; see properNoun.ts.
    const headwords = new Set(allLexemes.map((lexeme) => lexeme.headword));
    for (const name of ['tom', 'mary', 'boston', 'john']) {
      expect(headwords.has(name)).toBe(false);
    }
  });

  it('does teach the high-frequency words a beginner actually needs', () => {
    const headwords = new Set(allLexemes.map((lexeme) => lexeme.headword));
    for (const word of ['the', 'you', 'have', "i'm", 'because', 'english']) {
      expect(headwords.has(word)).toBe(true);
    }
  });
});
